In [1]:
import tensorflow as tf
import numpy as np
img = tf.random_uniform([10,28,28,3])
sess = tf.Session()
print(sess.run(img))

[[[[  1.48960948e-01   1.29799843e-02   1.92733407e-01]
   [  7.82159567e-02   4.39299941e-01   2.07862020e-01]
   [  2.60454535e-01   5.37586331e-01   4.28009033e-03]
   ..., 
   [  3.80619049e-01   4.61489201e-01   8.23964238e-01]
   [  7.37780333e-02   7.67524838e-01   7.14170933e-02]
   [  6.16959453e-01   3.29058170e-02   9.30021524e-01]]

  [[  5.32102227e-01   2.40260959e-01   6.11365676e-01]
   [  5.04833460e-02   4.56572533e-01   5.56705236e-01]
   [  4.79818583e-02   2.33087182e-01   2.76044369e-01]
   ..., 
   [  2.93179989e-01   8.65505099e-01   5.33867598e-01]
   [  2.01675892e-02   8.80442142e-01   2.04119325e-01]
   [  4.15980816e-03   8.59130979e-01   3.44591022e-01]]

  [[  5.77875376e-01   1.22382164e-01   7.53683329e-01]
   [  7.31858015e-02   4.73308086e-01   5.61423540e-01]
   [  1.89840078e-01   5.85719466e-01   6.85807109e-01]
   ..., 
   [  9.66609240e-01   5.37841320e-01   3.13035488e-01]
   [  8.44539642e-01   9.54904556e-01   6.49984241e-01]
   [  9.78218913e

In [2]:
img2 = img[1]
img2.shape

TensorShape([Dimension(28), Dimension(28), Dimension(3)])

In [3]:
img2_1 = tf.slice(img,[1,0,0,0],[1,28,28,3])
img2_1.shape

TensorShape([Dimension(1), Dimension(28), Dimension(28), Dimension(3)])

In [4]:
img_odd = img[0:8:2]
img_odd.shape

TensorShape([Dimension(4), Dimension(28), Dimension(28), Dimension(3)])

In [5]:
img_cen = img[6:8,7:21,7:21]
img_cen.shape

TensorShape([Dimension(2), Dimension(14), Dimension(14), Dimension(3)])

In [6]:
path1 = tf.slice(img,[0,0,0,0],[10,28,28,1])
path2 = tf.slice(img,[0,0,0,1],[10,28,28,2])
path3 = tf.slice(img,[0,0,0,2],[10,28,28,3])
print(path1.shape)
print(path2.shape)
print(path3.shape)

(10, 28, 28, 1)
(10, 28, 28, 2)
(10, 28, 28, 3)


In [7]:
shape = tf.shape(img)
rank = tf.rank(shape)
sess = tf.Session()
print(sess.run(rank))
sess = tf.Session()
print(sess.run(shape))

1
[10 28 28  3]
